import { Injectable } from '@nestjs/common';

import {
  AlertSeverity,
  AmlRuleKind,
  type AmlAlert,
  type AmlCase,
  type AmlRule,
} from '@reliance/contracts';

import { ClockService } from '../../common/clock/clock.service.js';

/**
 * In-memory AML store: rules, alerts and cases.
 *
 * Seeded with a representative set of rules. Alerts and cases start empty — they are
 * generated by the rule engine in a future increment. The store is process-local (dev/demo).
 *
 * A production implementation would use MongoDB with compound indexes on
 * `(status, raisedAt)` for alerts and `(status, openedAt)` for cases, and a Redis-backed
 * rule cache for the hot evaluation path.
 */
@Injectable()
export class AmlStore {
  private readonly rules: Map<string, AmlRule>;
  constructor(private readonly clock: ClockService) {
    this.rules = new Map(seedRules(clock.now().toISOString()).map((rule) => [rule.id, rule]));
  }
  private readonly alerts = new Map<string, AmlAlert>();
  private readonly cases = new Map<string, AmlCase>();

  // --- Rules ----------------------------------------------------------------

  listRules(): AmlRule[] {
    return [...this.rules.values()].sort((a, b) => a.name.localeCompare(b.name));
  }

  findRule(id: string): AmlRule | undefined {
    return this.rules.get(id);
  }

  upsertRule(rule: AmlRule): AmlRule {
    const updated = { ...rule, updatedAt: this.clock.now().toISOString() };
    this.rules.set(rule.id, updated);
    return updated;
  }

  // --- Alerts ---------------------------------------------------------------

  listAlerts(): AmlAlert[] {
    return [...this.alerts.values()].sort(
      (a, b) => new Date(b.raisedAt).getTime() - new Date(a.raisedAt).getTime(),
    );
  }

  // --- Cases ----------------------------------------------------------------

  listCases(): AmlCase[] {
    return [...this.cases.values()].sort(
      (a, b) => new Date(b.openedAt).getTime() - new Date(a.openedAt).getTime(),
    );
  }

  findCase(id: string): AmlCase | undefined {
    return this.cases.get(id);
  }
}

function seedRules(now: string): AmlRule[] {
  return SEED_RULE_DEFINITIONS.map((rule) => ({ ...rule, updatedAt: now }));
}

const SEED_RULE_DEFINITIONS: Array<Omit<AmlRule, 'updatedAt'>> = [
  {
    id: 'rule-velocity-01',
    kind: AmlRuleKind.VELOCITY,
    name: 'High-velocity outbound',
    description: 'More than 10 outbound transfers within a 24-hour window.',
    enabled: true,
    severity: AlertSeverity.HIGH,
    parameters: { windowHours: 24, count: 10 },
    alertsLast30Days: 0,
    falsePositiveRateBps: 0,
  },
  {
    id: 'rule-structuring-01',
    kind: AmlRuleKind.STRUCTURING,
    name: 'Structuring below reporting threshold',
    description: 'Multiple transfers just below the reporting threshold in a single day.',
    enabled: true,
    severity: AlertSeverity.CRITICAL,
    parameters: { thresholdAmount: '990000', windowHours: 24, count: 3 },
    alertsLast30Days: 0,
    falsePositiveRateBps: 0,
  },
  {
    id: 'rule-dormant-01',
    kind: AmlRuleKind.DORMANT_REACTIVATION,
    name: 'Dormant account reactivation with large credit',
    description: 'An account inactive for 90+ days receives a credit above £10,000.',
    enabled: true,
    severity: AlertSeverity.MEDIUM,
    parameters: { dormancyDays: 90, minAmount: '1000000' },
    alertsLast30Days: 0,
    falsePositiveRateBps: 0,
  },
  {
    id: 'rule-round-01',
    kind: AmlRuleKind.ROUND_AMOUNT,
    name: 'Repeated round-amount transfers',
    description: 'Three or more transfers with exactly round amounts within 48 hours.',
    enabled: false,
    severity: AlertSeverity.LOW,
    parameters: { windowHours: 48, count: 3 },
    alertsLast30Days: 0,
    falsePositiveRateBps: 0,
  },
];
