/**
 * Lending handlers: products, eligibility, applications and servicing.
 *
 * The illustrative schedule is generated by the same function the loan fixtures use, so
 * the quote a customer accepts and the loan they end up with agree instalment for
 * instalment.
 */

import {
  EntryType,
  ErrorCode,
  LoanApplicationStatus,
  routes,
  TransactionDirection,
  type Money,
} from '@reliance/contracts';

import type { MockClock } from '../db/clock.js';
import { findAccount, hasInsufficientFunds, postToAccount } from '../db/ledger.js';
import { addMoney, applyBps, minorUnits, money, zero } from '../db/money.js';
import { makeSchedule } from '../factories/products.js';
import { opaqueId } from '../faker.js';

import {
  failure,
  MockMethod,
  notFound,
  resourceCreated,
  resourceOk,
  route,
  type MockRoute,
} from './kit.js';
import { paginate, paginateStatic } from './paging.js';
import { readMoney } from './read-body.js';

const PAYOFF_VALIDITY_DAYS = 7;

/** Loans, applications and overdrafts. */
export const borrowHandlers: readonly MockRoute[] = [
  route(MockMethod.GET, routes.borrow.products, ({ db }) => paginateStatic(db.loanProducts)),

  route(MockMethod.POST, routes.borrow.calculate, ({ body, db }) => {
    const input = (body ?? {}) as Record<string, unknown>;
    const product = db.loanProducts.find((candidate) => candidate.code === input.productCode);
    if (!product) return notFound('That loan product');

    const amount = readMoney(body, 'amount') ?? money(500_000);
    const termMonths = Number(input.termMonths ?? 36);
    return resourceOk(
      quoteFor({
        clock: db.clock,
        productCode: product.code,
        amount,
        termMonths,
        aprBps: product.representativeAprBps,
      }),
    );
  }),

  route(MockMethod.POST, routes.borrow.eligibility, () => {
    const CREDIT_SCORE = 742;
    return resourceOk({
      eligible: true,
      maxAmount: money(2_000_000),
      indicativeAprBps: 799,
      creditScore: CREDIT_SCORE,
      debtToIncomeBps: 2_140,
      reasons: ['Consistent income for over twelve months', 'No missed payments on file'],
    });
  }),

  route(MockMethod.GET, routes.borrow.applications, ({ db, query }) => {
    const status = query.get('status');
    return paginate(
      db.loanApplications.filter((application) => !status || application.status === status),
      query,
    );
  }),

  route(MockMethod.POST, routes.borrow.applications, ({ body, db }) => {
    const input = (body ?? {}) as Record<string, unknown>;
    const product = db.loanProducts.find((candidate) => candidate.code === input.productCode);
    if (!product) return notFound('That loan product');

    const amount = readMoney(body, 'amount') ?? money(500_000);
    const termMonths = Number(input.termMonths ?? 36);
    const application = {
      id: opaqueId(),
      productCode: product.code,
      status: LoanApplicationStatus.OFFER_MADE,
      requestedAmount: amount,
      termMonths,
      purpose: String(input.purpose ?? 'General'),
      offer: quoteFor({
        clock: db.clock,
        productCode: product.code,
        amount,
        termMonths,
        aprBps: product.representativeAprBps,
      }),
      offerExpiresAt: db.clock.daysAhead(14),
      declineReasons: [],
      requiredDocumentKinds: [],
      submittedAt: db.clock.nowIso(),
      decidedAt: db.clock.nowIso(),
      createdAt: db.clock.nowIso(),
    };

    db.loanApplications.unshift(application);
    return resourceCreated(application);
  }),

  route(MockMethod.POST, routes.borrow.acceptOffer(':id'), ({ db, params }) => {
    const index = db.loanApplications.findIndex((candidate) => candidate.id === params.id);
    const application = db.loanApplications[index];
    if (index === -1 || !application) return notFound('That application');
    if (!application.offer) {
      return failure(ErrorCode.OFFER_EXPIRED, 'There is no live offer on this application.');
    }

    const accepted = { ...application, status: LoanApplicationStatus.DISBURSED };
    db.loanApplications[index] = accepted;
    return resourceOk(accepted);
  }),

  route(MockMethod.POST, routes.borrow.requestOverdraft, ({ body, db }) => {
    const application = {
      id: opaqueId(),
      productCode: 'RB-OVERDRAFT',
      status: LoanApplicationStatus.UNDER_REVIEW,
      requestedAmount: readMoney(body, 'limit') ?? money(50_000),
      termMonths: 0,
      purpose: 'Arranged overdraft',
      offer: null,
      offerExpiresAt: null,
      declineReasons: [],
      requiredDocumentKinds: [],
      submittedAt: db.clock.nowIso(),
      decidedAt: null,
      createdAt: db.clock.nowIso(),
    };
    db.loanApplications.unshift(application);
    return resourceCreated(application);
  }),

  route(MockMethod.GET, routes.borrow.application(':id'), ({ db, params }) => {
    const application = db.loanApplications.find((candidate) => candidate.id === params.id);
    return application ? resourceOk(application) : notFound('That application');
  }),

  route(MockMethod.DELETE, routes.borrow.application(':id'), ({ db, params }) => {
    const index = db.loanApplications.findIndex((candidate) => candidate.id === params.id);
    const application = db.loanApplications[index];
    if (index === -1 || !application) return notFound('That application');
    const withdrawn = { ...application, status: LoanApplicationStatus.WITHDRAWN };
    db.loanApplications[index] = withdrawn;
    return resourceOk(withdrawn);
  }),

  route(MockMethod.GET, routes.borrow.list, ({ db, query }) => {
    const status = query.get('status');
    return paginate(
      db.loans.filter((loan) => !status || loan.status === status),
      query,
    );
  }),

  route(MockMethod.GET, routes.borrow.schedule(':id'), ({ db, params, query }) => {
    const loan = db.loans.find((candidate) => candidate.id === params.id);
    if (!loan) return failure(ErrorCode.LOAN_NOT_FOUND, 'That loan was not found.');

    return paginateStatic(
      makeSchedule({
        clock: db.clock,
        principalMinor: minorUnits(loan.principal),
        aprBps: loan.aprBps,
        termMonths: loan.termMonths,
        paidInstalments: loan.instalmentsPaid,
      }).slice(0, Number(query.get('limit') ?? loan.termMonths)),
    );
  }),

  route(MockMethod.POST, routes.borrow.repay(':id'), ({ body, db, params }) => {
    const index = db.loans.findIndex((candidate) => candidate.id === params.id);
    const loan = db.loans[index];
    if (index === -1 || !loan) return failure(ErrorCode.LOAN_NOT_FOUND, 'That loan was not found.');

    const input = (body ?? {}) as Record<string, unknown>;
    const account = findAccount(db, String(input.fromAccountId ?? ''));
    if (!account) return failure(ErrorCode.ACCOUNT_NOT_FOUND, 'That account was not found.');

    const amount = readMoney(body, 'amount') ?? zero(account.currency);
    if (hasInsufficientFunds(account, amount)) {
      return failure(ErrorCode.INSUFFICIENT_FUNDS, 'There is not enough for this repayment.');
    }

    postToAccount(db, {
      accountId: account.id,
      amount,
      direction: TransactionDirection.DEBIT,
      type: EntryType.LOAN_REPAYMENT,
      description: `${loan.productName} repayment`,
    });

    const remaining = minorUnits(loan.outstandingBalance) - minorUnits(amount);
    const updated = {
      ...loan,
      outstandingBalance: money(remaining < 0n ? 0n : remaining, loan.principal.currency),
      instalmentsPaid: loan.instalmentsPaid + 1,
      instalmentsRemaining: Math.max(loan.instalmentsRemaining - 1, 0),
    };
    db.loans[index] = updated;
    return resourceOk(updated);
  }),

  route(MockMethod.GET, routes.borrow.payoffQuote(':id'), ({ db, params }) => {
    const loan = db.loans.find((candidate) => candidate.id === params.id);
    if (!loan) return failure(ErrorCode.LOAN_NOT_FOUND, 'That loan was not found.');

    const accrued = applyBps(loan.outstandingBalance, Math.round(loan.aprBps / 12));
    const fee = applyBps(loan.outstandingBalance, 100);
    return resourceOk({
      loanId: loan.id,
      outstandingPrincipal: loan.outstandingBalance,
      accruedInterest: accrued,
      earlyRepaymentFee: fee,
      interestRebate: zero(loan.principal.currency),
      totalPayable: addMoney(addMoney(loan.outstandingBalance, accrued), fee),
      validUntil: db.clock.daysAhead(PAYOFF_VALIDITY_DAYS),
    });
  }),

  route(MockMethod.GET, routes.borrow.byId(':id'), ({ db, params }) => {
    const loan = db.loans.find((candidate) => candidate.id === params.id);
    return loan ? resourceOk(loan) : failure(ErrorCode.LOAN_NOT_FOUND, 'That loan was not found.');
  }),
];

interface QuoteInput {
  readonly clock: MockClock;
  readonly productCode: string;
  readonly amount: Money;
  readonly termMonths: number;
  readonly aprBps: number;
}

function quoteFor({ amount, aprBps, clock, productCode, termMonths }: QuoteInput) {
  const schedule = makeSchedule({
    clock,
    principalMinor: minorUnits(amount),
    aprBps,
    termMonths,
  });
  const totalInterest = schedule.reduce((sum, row) => sum + minorUnits(row.interest), 0n);

  return {
    productCode,
    amount,
    termMonths,
    aprBps,
    monthlyPayment: schedule[0]?.payment ?? zero(amount.currency),
    totalRepayable: money(minorUnits(amount) + totalInterest, amount.currency),
    totalInterest: money(totalInterest, amount.currency),
    arrangementFee: zero(amount.currency),
    firstPaymentDate: clock.dateDaysAhead(30),
    schedule,
  };
}
